{{ if not .Values.app.cron }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-valid
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: {{ .Release.Name }}
spec:
  tls:
  - hosts:
      {{ if not (eq .Values.env "prod") }}
      - {{ .Values.ingress.host }}.{{ .Values.domain }}
      {{ else }}
      - {{ .Values.ingress.host }}
      {{ end }}
    secretName: {{ .Release.Name }}-tls
  rules:
  {{ if not (eq .Values.env "prod") }}
  - host: {{ .Values.ingress.host }}.{{ .Values.domain }}
  {{ else }}
  - host: {{ .Values.ingress.host }}
  {{ end }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.app.port }}
{{ end }}