name: Run tests

on:
  push:

jobs:
  main:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: yarn install

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Start app
      run: yarn start &

    - name: Wait for 30 seconds
      run: sleep 30s

    - name: Run tests
      run: yarn wdio

    - name: Discord Notification on Failure
      if: failure() && github.ref == 'refs/heads/master'
      uses: Ilshidur/action-discord@2.1.0
      with:
        args: "CI/CD Pipeline failed for repository: ${GITHUB_REPOSITORY}, at commit: ${GITHUB_SHA}. Check it out at ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        webhook: ${{ secrets.DISCORD_WEBHOOK_STARTUPJS_TESTS_FAILED }}
